### ISSUE TITLE
Parsing time of fizzbuzz

### ISSUE THREAD

**Issue by eduardo-imadeira** [alcides/aeon#46]
PR #31
while running the example "examples/PSB2/annotations/multi_objective/fizzbuzz.ae" I noticed it took a while to do the parsing, it took an average of over 25 second .

this is an example of one run
```
(.venv) ➜  aeon git:(metadata_in_decorators) $ python aeon examples/PSB2/annotations/multi_objective/fizzbuzz.ae --log INFO ERROR TYPECHECKER SYNTH_TYPE CONSTRAINT

Time to parse: 25.318535089492798
```
sometimes also happens with other examples, like "examples/PSB2/annotations/multi_objective/camel_case.ae".
camel_case took an average of over 28 second to execute the parsing progress

but most of the examples take less than a second to do the parsing

**Comment by alcides** [comment]
Fizzbuzz is not yet in that branch. Can you commit it?

**Comment by eduardo-imadeira** [comment]
my bad, I forgot to push the commits

**Comment by eduardo-imadeira** [comment]
The examples that the parsing was taking so long were the ones that I was using the textdistance package to calculate levenshtein distance. I simplified the way I am calculating the levenshtein distance and the time decreased to an average of 3 seconds.
