### ISSUE TITLE
RefinedType to Metahandler Union

### ISSUE THREAD

**Issue by eduardo-imadeira** [alcides/aeon#66]
Test : https://github.com/alcides/aeon/blob/03604a59f1dc8172d7c3840ed8b904dd0e886744/tests/intervals_test.py#L83

For example, from this refined type `{g:Int | (g > 0 && g < 10) || (g > 20 && g < 30)}`, the sympy expresion would be:
`((g > 0) & (g < 10)) | ((g > 20) & (g < 30))`
then transforming this sympy expression into a list of Relational objects we would get : `[g > 0, g < 10, g > 20, g < 30]`
 I would expect that when I use this list of Relational objects  as input of the sympy function `reduce_rational_inequalities` to get the object : `Union(Interval(0, 10), Interval(20, 30))` , but instead I am getting an `EmptySet`object (https://github.com/alcides/aeon/blob/03604a59f1dc8172d7c3840ed8b904dd0e886744/aeon/synthesis_grammar/grammar.py#L180)

**Comment by alcides** [comment]
I'll take a look at this later. @pcanelas, do you have idea about this?

**Comment by alcides** [comment]
Just a though:

If the list of relational objects is `[g > 0, g < 10, g > 20, g < 30]`, you are loosing the OR. And indeed, there is no value that is smaller than 10 AND greater than 20. 

After obtaining the sympy expression, you have to convert each (recursive) argument of OR into an interval.

The following pseudo-code should work. You are just missing the split step.
```
rt = "{g:Int | (g > 0 && g < 10) || (g > 20 && g < 30)}"
sympy_expr = convert_to_sympy(rt)
intervals = split("|", sympy_expr) # this needs to be a recursive function
metahandlers = map( interval_to_mh, intervals)
final_metahandler = fold(Union, meta handlers)
```
